### ISSUE TITLE
El CSS debe contar con un estilo por id

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#10]
Revisar la siguiente diapositiva de clase:
https://ucc-labcompu2.github.io/filminas/U4_CSS.html#/15

**Comment by KindGuyJ** [comment]
Ya habia:
#teniaqueusarasi {
    font-size: 5em;
}

**Comment by edme88** [comment]
Tenés razón, me equivoque en la corrección (son 5% más)
