### ISSUE TITLE
Sugerencia: Corregir errores de ortografía - Mensajes de error del usuario

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#11]
Inválido lleva tilde. Quizás en el contexto de mensajes de usuario, sería mejor colocar "Debe ingresar un teléfono correcto.". 
Es mejor que los mensajes de usuario sean positivos.

![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/d77feb3a-2e56-457a-bd04-25d98fc87451)

**Comment by KindGuyJ** [comment]
Corregido
