### ISSUE TITLE
Verificación incorrecta en edad

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#13]
Complete la edad primero empleando letras, luego presione enviar.
Fue correcto el mensaje y me eliminó el contenido.
Pero ahora deje la edad vacía y me dice de error que no contratan menores de edad, en lugar de decirme que debo ingresar una edad.
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/4c459d28-1d70-4b9b-9bc4-ac45348b7b47)

**Comment by KindGuyJ** [comment]
Solucionado en main
