### ISSUE TITLE
Validaciones incorrectas en teléfono

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#14]
Ingresé un número de teléfono correcto y se visualiza mensaje de error:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/bfc302e3-0a5a-420e-b7a9-27a93fd6378b)

**Comment by KindGuyJ** [comment]
Clarifique el error, el numero de teléfono debe estar acompañado de un +54 o alguna otra característica de un país.
