### ISSUE TITLE
Los campos continuan visualizandose en rojo pese a que se corrigió su contenido

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#15]
Primero completé el formulario todo incorrecto, y todos los campos se pintaron de rojo (lo cual es correcto).
Pero, una vez que corregí los valores y presiono enviar de nuevo, aquellos que sean correctos NO deben estar pintados de rojo.

![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/87a122d6-9e82-459e-b7e1-1bc060cbfa82)

**Comment by KindGuyJ** [comment]
Fixed
