### ISSUE TITLE
El formulario permite realizar el envio SIN completar la experiencia

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#16]
En caso de que un formulario posea campos que son obligatorios y campos que no lo son, es importante que se agregue un asterisco o una forma de marcar aquellos que sean "mandatorios u obligatorios" de aquellos que no lo sean.

En el caso de que todos los campos sean obligatorio, eso no es necesario (pero tenés que verificar que efectivamente la parte de experiencia NO esté vacia).

**Comment by KindGuyJ** [comment]
Intended behaviour, added optional for clarification
