### ISSUE TITLE
Si una variable NO va a sobre-escribirse, debería ser declarada como const

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#18]
https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/5c9f43b78fb51faf788650ba5a468b07777eab91/Funciones.js#L2

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/5c9f43b78fb51faf788650ba5a468b07777eab91/Funciones.js#L48

**Comment by KindGuyJ** [comment]
Ya implementando en main
