### ISSUE TITLE
Identar correctamente el código

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#3]
Identar correctamente el código (en Webstorm con Ctrol+A se selecciona todo el código y con Ctrl+Alt+L ó menú Code > Reformat Code)

**Comment by KindGuyJ** [comment]
Uso vs code, esta indentando por format document, a no ser que haya hecho un cambio que olvide. Voy a reformatear todo

**Comment by KindGuyJ** [comment]
No lo reformatie, el codigo estaba correctamente indentado en la fecha de entrega

**Comment by edme88** [comment]
Revisé la identación con WebStorm y veo que los siguientes archivos marcados en celeste, para WebStorm no están correctamente identados:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/487ee4c2-026b-4f80-91e6-8995e5d59c42)

Ejemplo de ejecución de un **git diff**:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/assets/8345007/3774de43-4903-4f8d-b823-68e71e6d7ab1)
Lo verde indica mi código, y lo rojo indica tu código. Es decir, todo el verde se desplaza a la izquierda un tab, porque el body y la primera parte de su contenido está al mismo nivel.

Que en clase empleemos WebStorm, y que yo pida que usen WebStorm no es caprichoso, es para que todos manejemos el mismo standard. Sino pasan estas cosas.

Tuve que revisar la identación MANUALMENTE, porque no sé que tipo de configuración de linting usaste. (y eso me hizo perder mucho tiempo).
Habitualmente en los proyectos dentro de las empresas para que este tipo de errores de identaci[on y espacios no existan, todos los desarrolladores realizan la misma configuración de linting y formating. 

Para la SEGUNDA ENTREGA SI O SI presenta el código formateado en WebStorm, porque no volveré a corregir la identación de manera manual.
