### ISSUE TITLE
Emplear el atributo size para que el tamaño de los inputs sea prolijo

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#7]
https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L31

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L36

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L53

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L58

**Comment by KindGuyJ** [comment]
No conozco el atributo, lo voy a agregar

**Comment by edme88** [comment]
Lo vimos en clase a ese atributo y hasta lo usamos en un ejercicio:
https://ucc-labcompu2.github.io/filminas/U4_HTML_avanzado.html#/15
