### ISSUE TITLE
No espaciar con excesivos <br>

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-fernandez-favaron#9]
No espaciar con excesivos <br>. Utilizar márgenes, paddings, etc.

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/index.html#L29

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/index.html#L42

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/index.html#L54

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L27

https://github.com/UCC-LabCompu2/proyecto2024-fernandez-favaron/blob/9e0417d4267dc856cb7b5d11e3e49ee0e4c1b37c/formulario.html#L86

**Comment by KindGuyJ** [comment]
Solucionado mediante el uso de padding
